# Generated by Django 4.2.11 on 2024-04-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meditation',
            fields=[
                ('meditation_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Meditation ID')),
                ('user_id', models.IntegerField()),
                ('video_url', models.URLField()),
                ('audio_url', models.URLField()),
            ],
        ),
    ]
