# Generated by Django 4.2.11 on 2024-05-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meditations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meditation',
            name='audio_url',
        ),
    ]
