version: "3.9"
services:
  django:
    environment:
      - "DJANGO_ALLOWED_HOSTS=${MY_DOMAIN}"
      - "DJANGO_CSRF_TRUSTED_ORIGINS=https://${MY_DOMAIN}"
      - "DJANGO_SESSION_COOKIE_SECURE=true"
      - "DJANGO_CSRF_COOKIE_SECURE=true"
      - "DJANGO_SECURE_SSL_REDIRECT=true"
    labels:
      - "traefik.http.routers.production.rule=Host(`${MY_DOMAIN}`)"
      - "traefik.http.routers.production.entrypoints=websecure"
      - "traefik.http.routers.production.tls.certresolver=le-resolver"
      - "traefik.http.routers.production.priority=1"

  nginx:
    labels:
      - "traefik.http.routers.staticfiles.entrypoints=websecure"
      - "traefik.http.routers.staticfiles.tls.certresolver=le-resolver"
