# Generated by Django 4.2.11 on 2024-04-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('analytics_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Analytics ID')),
                ('user_id', models.IntegerField()),
                ('days_of_journaling', models.IntegerField()),
                ('positive_keywords', models.IntegerField()),
                ('negative_keywords', models.IntegerField()),
                ('date_window_weekly', models.DateField(verbose_name='Weekly Analytics')),
                ('mood', models.IntegerField()),
            ],
        ),
    ]
