from django.db import models

# Calendar Models
class Calendar(models.Model):
    calendar_id = models.IntegerField(primary_key=True, serialize=False, verbose_name='Calendar ID')
    user_id = models.IntegerField()
    event_id = models.IntegerField()
    title = models.CharField(max_length=200)
    start_date = models.DateField('Start Date')
    end_date = models.DateField('End Date')
    start_time = models.TimeField('Start Time')
    end_time = models.TimeField('End Time')
    location = models.CharField(max_length=200)
    description = models.TextField()
    all_day = models.BooleanField()
    recurring = models.BooleanField()
    recurrence = models.CharField(max_length=200)
    reminder = models.BooleanField()
    reminder_time = models.TimeField('Reminder Time')
    reminder_date = models.DateField('Reminder Date')
    reminder_email = models.EmailField()
    reminder_sms = models.CharField(max_length=200)
    reminder_popup = models.BooleanField()
    reminder_sound = models.CharField(max_length=200)
    reminder_repeat = models.BooleanField()
    reminder_repeat_interval = models.CharField(max_length=200)
    reminder_repeat_end_date = models.DateField('Reminder Repeat End Date')
    reminder_repeat_end_time = models.TimeField('Reminder Repeat End Time')
    reminder_repeat_occurrences = models.IntegerField()
    reminder_repeat_days = models.CharField(max_length=200)
    reminder_repeat_weeks = models.CharField(max_length=200)
    reminder_repeat_months = models.CharField(max_length=200)
    reminder_repeat_years = models.CharField(max_length=200)
    reminder_repeat_day_of_week = models.CharField(max_length=200)
    reminder_repeat_day_of_month = models.CharField(max_length=200)
    reminder_repeat_day_of_year = models.CharField(max_length=200)
    reminder_repeat_day_of_week_of_month = models.CharField(max_length=200)
    reminder_repeat_day_of_year_of_month = models.CharField(max_length=200)
    reminder_repeat_day_of_week_of_year = models.CharField(max_length=200)
    reminder_repeat_day_of_month_of_year = models.CharField(max_length=200)
    reminder_repeat_day_of_week_of_month_of_year = models.CharField(max_length=200)
    reminder_repeat_day_of_week_of_year_of_month = models.CharField(max_length=200)
    reminder_repeat_day_of_week_of_month_of_year = models.CharField(max_length=200)
    reminder_repeat_day_of_week_of_year_of_month = models.CharField(max_length=200)
    reminder_repeat_day_of_week_of_month_of_year = models.CharField(max_length=200)