# Generated by Django 4.2.11 on 2024-05-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='User ID')),
                ('username', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('verified_email', models.BooleanField()),
                ('password', models.CharField()),
                ('account_created_date', models.DateField()),
                ('first_name', models.CharField()),
                ('middle_name', models.CharField()),
                ('last_name', models.CharField()),
                ('birth', models.DateField()),
                ('theme', models.CharField()),
                ('notifications', models.BooleanField()),
                ('meditation_tab', models.BooleanField()),
            ],
        ),
    ]
