# Generated by Django 4.2.11 on 2024-05-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='username',
            field=models.CharField(),
        ),
    ]
