# Generated by Django 4.2.11 on 2024-05-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_field', models.TextField()),
                ('char_field', models.CharField()),
                ('int_field', models.IntegerField()),
                ('boolean_field', models.BooleanField()),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=100)),
                ('time_field', models.TimeField()),
                ('date_field', models.DateField()),
                ('url_field', models.URLField()),
            ],
        ),
    ]
