# Generated by Django 4.2.11 on 2024-05-01 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestTable',
            new_name='Test',
        ),
    ]
