# Generated by Django 4.2.11 on 2024-04-26 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='test',
        ),
    ]
