# Generated by Django 4.2.11 on 2024-04-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_alter_journal_entry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Tag ID')),
                ('journal_id', models.IntegerField()),
                ('tag_name', models.CharField(max_length=200)),
                ('tag_color', models.CharField(max_length=10)),
            ],
        ),
    ]
